### ISSUE TITLE
Autocomplete list interferes with use on slow connections

### ISSUE THREAD

**Issue by dkumor** [tehbmar/easy-keybase.io-encryption-extension#3]
When on a slow/lossy connection, the user autocomplete list falls well behind the typing, and sometimes (if requests become out of order), does not complete final text. Sometimes, I can type a username, and it slowly iterates through the letters for the next ~15 seconds, blocking the encrypt message textbox.

This is presumably because the list is updated on each keystroke, and the previous request is not canceled if it is not yet complete. If the final autocomplete update finishes before a previous one, I am guessing it overwrites the list.

A possible fix would be to show autocomplete only when the user input textbox is focused (an updating autocomplete makes the extension unusable if I try to type in a username and encrypt a message while it is not finished), and possibly ensuring that autocomplete responses are ordered correctly.

**Comment by 0x4445565A** [comment]
I have actually noticed this, I'm out of the country and have had some issues with internet speeds.

I'll get on this and figure out how to drop the connections and only show during name input focus.

Thank you for the report!

**Comment by 0x4445565A** [comment]
https://github.com/tehbmar/easy-keybase.io-encryption-extension/commit/18154e1dc99a7fa649edb905269ad022680e2358

I wrote this up, I think this should be enough for now.  I'm planning on doing a ground up rewrite of the extension so the code fix might not look the most natural in there haha.

But this should work, I'll leave it in the repo and if you could test it a bit and let me know.  If there aren't any issues I'll update the google chrome plugin in the store.
